{
 "title": "Toncenter UX",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "getMasterChainInfo response time",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 }
  },
  {
   "title": "getMasterChainInfo success",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * increase(getMasterchainInfo_success_total[$__range]) / (increase(getMasterchainInfo_success_total[$__range]) + increase(getMasterchainInfo_failure_total[$__range])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "getAddressBalance response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(getAddressBalance_time_sum{}[30s]) )/ sum(rate(getAddressBalance_time_count{}[30s]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "getAddressBalance success",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * increase(getAddressBalance_success_total[$__range]) / (increase(getAddressBalance_success_total[$__range]) + increase(getAddressBalance_failure_total[$__range])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "transactionsByMasterchainBlock response time",
   "type": "timeseries",
   "description": "On random block from 33000000 to the last  known one. By metric design, should be run once in 20s.",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(transactionsByMasterchainBlock_time_sum{}[30s]) )/ sum(rate(transactionsByMasterchainBlock_time_count{}[30s]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "transactionsByMasterchainBlock success",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * increase(transactionsByMasterchainBlock_success_total[$__range]) / (increase(transactionsByMasterchainBlock_success_total[$__range]) + increase(transactionsByMasterchainBlock_failure_total[$__range])) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}